# Generated by Django 5.0.4 on 2024-04-26 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_customuser_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lecturer Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Lecturer Surname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
            },
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturers',
            field=models.ManyToManyField(related_name='subjects', to='student.lecturer'),
        ),
    ]
