# Generated by Django 5.0.4 on 2024-04-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_lecturer_delete_lecture_alter_subject_lecturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submission Date'),
        ),
    ]
